$(function () {
  $("#stage").scant()
    .make("#origin-bg.bg-rect").at(0, 0).size(600, 390)
    .make("#origin-repo.label Origin").at(20, 20)
    .make("#origin-master-1.commit a09351f").at(20, 100)
    .make("#origin-master-2.commit 01faf34").rightOf("#origin-master-1").connect()
    .make("#origin-master.branch master").above("#origin-master-2").connect()
    .make("#local-bg.bg-rect").at(0, 400).size(600, 400)
    .make("#local-repo.label Local Repo").at(20, 420)
    .make("#local-master-1.commit a09351f").at(20, 570)
    .make("#local-master-2.commit 01faf34").rightOf("#local-master-1").connect()
    .make("#local-master.branch master").above("#local-master-2").connect()
    .make("#local-HEAD.head HEAD").above("#local-master").connect()
    .make("#local-origin-master.branch.remote origin/master").below("#local-master-2").connect()
    
    .next()
    .fadeIn("#cmd-origin-new-commit")
    .make("#origin-master-3.commit.origin 993cda2").rightOf("#origin-master-2").connect()
        .fadeIn()
//    .then()
//    .move("#origin-master").above("#origin-master-3").connect()
//    
//    .next()
//    .fadeIn("#cmd-local-new-commits")
//    .make("#local-master-3.commit.local 6dc9032").rightOf("#local-master-2").connect()
//        .fadeIn()
//    .make("#local-master-4.commit.local 3018fa1").rightOf("#local-master-3").connect()
//        .fadeIn()
//    .then()
//    .group("#local-master", "#local-HEAD")
//        .move().above("#local-master-4").connect("#local-master")
//    
//    .next()
//    .fadeIn("#cmd-fetch-origin")
//    .clone("#origin-master-3", "#local-origin-3")
//        .fadeIn()
//        .move().below("#local-master-3")
//        .then()
//        .connect("#local-master-2")
//    .then()
//    .move("#local-origin-master").below("#local-origin-3").connect()
    
    .go();
});
