$(function () {
  $("#stage").scant()
    .make("#origin-bg.bg-rect").at(0, 0).size(600, 390)
    .make("#origin-repo.label Origin").at(20, 20)
    .make("#origin-master-1.commit a09351f").at(20, 100)
    .make("#origin-master-2.commit 01faf34").connect().rightOf("#origin-master-1")
    .make("#origin-master.branch master").connect().above("#origin-master-2")
    .make("#local-bg.bg-rect").at(0, 500).size(600, 400)
    .make("#local-repo.label Local Repo").at(620, 420)
    .make("#local-master-1.commit a09351f").at(620, 620)
    .make("#local-master-2.commit 01faf34").connect().rightOf("#local-master-1")
    .make("#local-master.branch master").connect().above("#local-master-2")
    .make("#local-HEAD.head HEAD").connect().above("#local-master")
    .make("#local-origin-master.branch.remote origin/master").connect().below("#local-master-2")
    
    .click()
    .fadeIn("#cmd-origin-new-commit")
    .make("#origin-master-3.commit.origin 993cda2").connect().rightOf("#origin-master-2")
        .fadeIn()
    .then()
    .move("#origin-master").connect().above("#origin-master-3")
    
    .click()
    .fadeIn("#cmd-local-new-commits")
    .make("#local-master-3.commit.local 6dc9032").connect().rightOf("#local-master-2")
        .fadeIn()
    .make("#local-master-4.commit.local 3018fa1").connect().rightOf("#local-master-3")
        .fadeIn()
    .then()
    .group("#local-master", "#local-HEAD")
        .move().connect("#local-master").above("#local-master-4")
    
    .click()
    .fadeIn("#cmd-fetch-origin")
    .clone("#origin-master-3", "#local-origin-3")
        .fadeIn()
        .move().below("#local-master-3")
        .then()
        .connect().to("#local-master-2")
    .then()
    .move("#local-origin-master").connect().below("#local-origin-3")
    
    .go();
});
